version: '3.8'

services:
  dotnet:
    image: devastation/dotnet:latest
    build:
      context: ./dotnet
      args:
        USERNAME: ${USER:-dev}
    volumes:
      - ./:/project
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=devastation;Username=postgres;Password=postgres
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: /usr/local/bin/dotnet-entrypoint.sh

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: devastation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: