@startuml devastation_architecture


' Set the layout direction to top to bottom
top to bottom direction
skinparam linetype ortho

' Define components
rectangle "base" as base
rectangle ".net" as dotnet
rectangle "go" as go
rectangle "python" as python
rectangle "rust" as rust
rectangle "kubernetes" as k8s
rectangle "your\nproject" as your1
rectangle "your\nproject" as your2

' Define relationships
base --> dotnet
base --> go
base --> python
base --> rust
base --> k8s

dotnet --> your1
python --> your2

@enduml