@startuml base_architecture

title base devastation components

hide circle
hide stereotypes

class "base devastation" as BaseDev {
  -- <color:ORANGE><b>os</b></color> --
  ubuntu 22.04 lts
  
  -- <color:ORANGE><b>shell environment</b></color> --
  zsh + oh-my-zsh
  powerlevel10k theme
  meslo nerd font
  tmux
  
  -- <color:ORANGE><b>development tools</b></color> --
  git
  node.js 20
  curl / fd-find / ripgrep
  gcc / make
  plantuml
  tree
  atuin (shell history)
  claude code cli
  
  -- <color:ORANGE><b>neovim</b></color> --
  lazy (plugin manager)
  telescope (fuzzy finder)
  neo-tree (file browser)
  base lsp support
  treesitter (syntax)
  completion (nvim-cmp)
  dap (debugging)
  git integration
  lualine (status)
}

@enduml
