@startuml base_architecture

!theme crt-amber

title base devastation components

hide circle
hide stereotypes
class "base devastation" as BaseDev {
  Theme crt-amber
  
  -- <b>os</b> --
  ubuntu 22.04 lts
  
  -- <b>shell environment</b> --
  zsh + oh-my-zsh
  powerlevel10k theme
  meslo nerd font
  tmux
  
  -- <b>development tools</b> --
  git
  node.js 20
  curl / fd-find / ripgrep
  gcc / make
  plantuml
  tree
  atuin (shell history)
  claude code cli
  
  -- <b>neovim</b> --
  lazy (plugin manager)
  telescope (fuzzy finder)
  neo-tree (file browser)
  base lsp support
  treesitter (syntax)
  completion (nvim-cmp)
  dap (debugging)
  git integration
  lualine (status)
}

@enduml
