@startuml cluster_architecture


title cluster devastation components

hide circle
hide stereotypes

class "cluster devastation" as ClusterDev {
  -- <color:ORANGE><b>kubernetes tools</b></color> --
  kubectl
  helm
  
  -- <color:ORANGE><b>cloud tools</b></color> --
  aws cli v2
  terraform
  
  -- <color:ORANGE><b>neovim cluster extensions</b></color> --
  terraform lsp
  yaml lsp
  kubernetes treesitter
  terraform treesitter
  yaml treesitter
  json treesitter
  bash treesitter
}

@enduml