@startuml cluster_architecture

!theme crt-amber

title cluster devastation components

hide circle
hide stereotypes

class "cluster devastation" as ClusterDev {
  Theme crt-amber
  -- <b>kubernetes tools</b> --
  kubectl
  helm
  
  -- <b>cloud tools</b> --
  aws cli v2
  terraform
  
  -- <b>neovim cluster extensions</b> --
  terraform lsp
  yaml lsp
  kubernetes treesitter
  terraform treesitter
  yaml treesitter
  json treesitter
  bash treesitter
}

@enduml
