@startuml dotnet_architecture

!theme crt-amber

title dotnet devastation components

hide circle
hide stereotypes

class "dotnet devastation" as DotnetDev {
  Theme crt-amber
  -- <b>dotnet sdks</b> --
  dotnet 8 sdk
  dotnet 9 sdk
  
  -- <b>neovim dotnet extensions</b> --
  c# treesitter
}

@enduml
