@startuml dotnet_architecture


title dotnet devastation components

hide circle
hide stereotypes

class "dotnet devastation" as DotnetDev {
  -- <color:ORANGE><b>dotnet sdks</b></color> --
  dotnet 8 sdk
  dotnet 9 sdk
  
  -- <color:ORANGE><b>neovim dotnet extensions</b></color> --
  c# treesitter
}

@enduml