@startuml python_architecture

!theme crt-amber

title python devastation components

hide circle
hide stereotypes

class "python devastation" as PyDev {
  Theme crt-amber
  -- <b>python runtime</b> --
  python 3.11
  
  -- <b>python tools</b> --
  poetry (package manager)
  debugpy
  pytest
  
  -- <b>neovim python extensions</b> --
  python lsp server
  python treesitter
  python dap support
}

@enduml
