@startuml python_architecture


title python devastation components

hide circle
hide stereotypes

class "python devastation" as PyDev {
  -- <color:ORANGE><b>python runtime</b></color> --
  python 3.11
  
  -- <color:ORANGE><b>python tools</b></color> --
  poetry (package manager)
  debugpy
  pytest
  
  -- <color:ORANGE><b>neovim python extensions</b></color> --
  python lsp server
  python treesitter
  python dap support
}

@enduml